// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlroxhg7J_8-C43GpzzDWjgEn2dVmTfXk',
    appId: '1:472793401024:web:3ed20eb507ba730a398f25',
    messagingSenderId: '472793401024',
    projectId: 'bus-app-c3cff',
    authDomain: 'bus-app-c3cff.firebaseapp.com',
    storageBucket: 'bus-app-c3cff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs_C1Ga_12Gwd__ZxgdIKGb6ccSKRtu3M',
    appId: '1:472793401024:android:2a22af3717493757398f25',
    messagingSenderId: '472793401024',
    projectId: 'bus-app-c3cff',
    storageBucket: 'bus-app-c3cff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmltzP87uzzpf4y-xJgkF0MNx-mJZu1Vs',
    appId: '1:472793401024:ios:12fdbe1a11d5cd6b398f25',
    messagingSenderId: '472793401024',
    projectId: 'bus-app-c3cff',
    storageBucket: 'bus-app-c3cff.firebasestorage.app',
    iosBundleId: 'com.example.busapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmltzP87uzzpf4y-xJgkF0MNx-mJZu1Vs',
    appId: '1:472793401024:ios:12fdbe1a11d5cd6b398f25',
    messagingSenderId: '472793401024',
    projectId: 'bus-app-c3cff',
    storageBucket: 'bus-app-c3cff.firebasestorage.app',
    iosBundleId: 'com.example.busapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlroxhg7J_8-C43GpzzDWjgEn2dVmTfXk',
    appId: '1:472793401024:web:35262be994f2f6c1398f25',
    messagingSenderId: '472793401024',
    projectId: 'bus-app-c3cff',
    authDomain: 'bus-app-c3cff.firebaseapp.com',
    storageBucket: 'bus-app-c3cff.firebasestorage.app',
  );
}
